### ISSUE TITLE
体幹キープ系アルゴリズム

### ISSUE THREAD

**Issue by kazuminn** [ie-ModelingAndDesign/2015-F#9]
体幹をキープしてるかどうか判断するアルゴリズムが思い浮かばない。

NSTimerって時間測る機能がある。
これだと、時間測るだけなので、ただぼーっとしてるだけでもクリアーしちゃう。

**Comment by MireiYUTAKA** [comment]
個人的には時間測るだけで良いと思います！
キープしているのの判定にジャイロ判定を加えたとして、ただ持ってるだけでも同じ判定なっちゃう気がするのでー…
他に何か良いのかないかな…(｡-_-｡)

**Comment by kazuminn** [comment]
うーん。そうですね。
腹筋のやつも、実際に腹筋をやらなくても
腹筋やってる感じに振れば、カウントしちゃうので、
とりあえず、
時間のやつで実装してみます。
